services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-container
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - postgres-internal

  postgres-internal:
    container_name: postgres-internal
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h localhost" ]
      interval: 2s
      timeout: 1s
      retries: 5